### ISSUE TITLE
leftNavSlider UI Script is not in the Update Set

### ISSUE THREAD

**Issue by krysbzh** [platform-experience/serviceportal-widget-library#104]
Widget "Navigation - Left Collapsible"

Hi,
I installed and all the portals crashed. In fact, it misses the UI script containing the module "leftNavSlider" in the update set. There is only the Widget Dependency.
Could you package it please?

Christophe

**Comment by cjstoll** [comment]
I have validated that the UI Script is part of the Update Set.  
If you go to the Retrieved Update Sets in your instance, select the update set, then in the Customer Updates tab ( make sure you have the 'Type' column showing ) sort by Type in ascending order.
You will see that the record is the 7th item in the list.
I have also verified by looking at the raw text of the update set - the payload starts on line 1774 (depending on your text editor) but you can search for 'sys_ui_script' and find it.

Did you get any errors when you previewed the update set before commit?

**Comment by krysbzh** [comment]
Hello Chris,
sorry, you are right, the UI Script is correctly pakaged. Actually, the dependency "m2m_sp_dependency_js_include" is missing (relation between "leftNavSlider" Widget dependency and the JS Include "leftNavSlider").

The Widget Dependency is included on the page load so the has an impact to all portals (/sp, /sp_config...)

Regards
Christophe

**Comment by cjstoll** [comment]
Yeah, the references were missing.
Fixed and uploaded new update set.
See if that fixes everything.
