### ISSUE TITLE
Site now requires authentication

### ISSUE THREAD

**Issue by jacebenson** [platform-experience/serviceportal-widget-library#168]
How can I get to the great content you all shared here: https://innovations.service-now.com/library ?

**Comment by NRS004** [comment]
I'm trying to figure out the same thing. I really enjoyed the site and it was shown to me by my former account rep. It was a really valuable resource and I hope you're not getting rid of it!

**Comment by jacebenson** [comment]
And they updated their page to say... it's moving to "share" 
![image](https://user-images.githubusercontent.com/638764/75750563-1739fb80-5cea-11ea-9060-b667197808ce.png)

**Comment by krysbzh** [comment]
Thanks Jace for the update ;)
